In [3]:
import numpy as np

# task1


In [11]:
random_array = np.random.randint(0, 100, (4, 4))  
sequence_array = np.arange(1, 16, 2)  
ones_array = np.ones(9, dtype=int)  
zeros_array = np.zeros((2, 4), dtype=float) 
linspace_array = np.linspace(0, 1, 5)  
random_float_array = np.random.random((4, 3))  

print("\nrandom_array\n", random_array)
print("\nsequence_array\n", sequence_array)
print("\nones_array\n", ones_array)
print("\nzeros_array\n", zeros_array)
print("\nlinspace_array\n", linspace_array)
print("\nrandom_float_array\n", random_float_array)


random_array
 [[37  9  0 36]
 [70 96 88 50]
 [80 33 75 91]
 [51 60 48 29]]

sequence_array
 [ 1  3  5  7  9 11 13 15]

ones_array
 [1 1 1 1 1 1 1 1 1]

zeros_array
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

linspace_array
 [0.   0.25 0.5  0.75 1.  ]

random_float_array
 [[0.94581489 0.95441101 0.08510103]
 [0.15643711 0.81709364 0.86053585]
 [0.33803033 0.0584294  0.22359968]
 [0.11381585 0.75235253 0.19290847]]


In [ ]:
sample_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("element with index 1:", sample_array[1]) 
print("last element from first array:", sample_array[0, -1])

sub_array = sample_array[1:, :2]  
print("subarray:\n", sub_array)

element with index 1: [4 5 6]
last element from first array: 3
subarray:
 [[4 5]
 [7 8]]


In [20]:
array_a = np.ones(4)
print("multiply 3 by ones:", np.multiply(array_a, 3))
print("adding 2 to ones:", array_a + 2)


multiply 3 by ones: [3. 3. 3. 3.]
adding 2 to ones: [3. 3. 3. 3.]


In [31]:
arr = np.arange(0, 6)
print("array: " , arr)
print("Reduce:", np.add.reduce(arr))
print("Accumulate:", np.add.accumulate(arr))

arr1 = np.arange(5, 10)
arr2 = np.arange(10, 20)
print("Outer :\n", np.add.outer(arr1, arr2))

array:  [0 1 2 3 4 5]
Reduce: 15
Accumulate: [ 0  1  3  6 10 15]
Outer :
 [[15 16 17 18 19 20 21 22 23 24]
 [16 17 18 19 20 21 22 23 24 25]
 [17 18 19 20 21 22 23 24 25 26]
 [18 19 20 21 22 23 24 25 26 27]
 [19 20 21 22 23 24 25 26 27 28]]


# task2

## а) Вивести основні статистичні характеристики кількісних ознак; <br>б) Знайти автомобілі на дизельному паливі з автоматичною коробкою передач, які дешевші за 15 тис;<br> в) Додати новий стовпець, який містить інформацію, скільки відсотків від ціни складає податок. 

In [8]:
import pandas as pd
import requests

In [17]:
filePath = "data/merc.csv"
df = pd.read_csv(filePath)
df

model  year  price transmission  mileage fuelType  tax   mpg  \
0            SLK  2005   5200    Automatic    63000   Petrol  325  32.1   
1        S Class  2017  34948    Automatic    27000   Hybrid   20  61.4   
2       SL CLASS  2016  49948    Automatic     6200   Petrol  555  28.0   
3        G Class  2016  61948    Automatic    16000   Petrol  325  30.4   
4        G Class  2016  73948    Automatic     4000   Petrol  325  30.1   
...          ...   ...    ...          ...      ...      ...  ...   ...   
1497     V Class  2018  21996       Manual    32095   Diesel  145  46.3   
1498     V Class  2018  19346       Manual    34483   Diesel  150  46.3   
1499     V Class  2019  20391    Automatic    18812   Diesel  150  48.7   
1500   GLA Class  2019  20995       Manual     6587   Petrol  145  40.9   
1501     C Class  2018  19950    Semi-Auto    33082   Diesel  145  64.2   

      engineSize  
0            1.8  
1            2.1  
2            5.5  
3            4.0  
4            4.0  
...          ...  
1497         2.1  
1498         2.1  
1499         2.1  
1500         1.6  
1501         2.1  

[1502 rows x 9 columns]

In [19]:
numeric_data = df[['year', 'price', 'mileage', 'tax', 'mpg', 'engineSize']]
numeric_data

year  price  mileage  tax   mpg  engineSize
0     2005   5200    63000  325  32.1         1.8
1     2017  34948    27000   20  61.4         2.1
2     2016  49948     6200  555  28.0         5.5
3     2016  61948    16000  325  30.4         4.0
4     2016  73948     4000  325  30.1         4.0
...    ...    ...      ...  ...   ...         ...
1497  2018  21996    32095  145  46.3         2.1
1498  2018  19346    34483  150  46.3         2.1
1499  2019  20391    18812  150  48.7         2.1
1500  2019  20995     6587  145  40.9         1.6
1501  2018  19950    33082  145  64.2         2.1

[1502 rows x 6 columns]

In [36]:
auto_diesel_automatic_price_lg_15k = df.query("fuelType == 'Diesel' and transmission == 'Automatic' and price < 15000")
# auto_diesel_automatic_price_lg_15k = df[(df.fuelType == 'Diesel') & (df.transmission == 'Automatic') & (df.price < 15000)]

print("len: ", len(auto_diesel_automatic_price_lg_15k))
auto_diesel_automatic_price_lg_15k


len:  23


model  year  price transmission  mileage fuelType  tax   mpg  \
49       A Class  2006   2880    Automatic    66000   Diesel  160  52.3   
51       C Class  2015  14940    Automatic    43000   Diesel   20  64.2   
59       E Class  2015  13990    Automatic    52000   Diesel  125  60.1   
62       C Class  2014  11290    Automatic    48000   Diesel  145  56.5   
66       B Class  2015  11240    Automatic    47000   Diesel  125  56.5   
71       M Class  2008   5990    Automatic   110000   Diesel  555  28.8   
72       A Class  2013   7300    Automatic    54000   Diesel   30  65.7   
74      GL Class  2007   7340    Automatic   104000   Diesel  570  28.8   
75      GL Class  2007   8490    Automatic    74000   Diesel  570  28.8   
76       C Class  2009   4480    Automatic   130000   Diesel  300  37.7   
79       E Class  2007   4880    Automatic    58000   Diesel  315  37.2   
128      A Class  2014  11980    Automatic    66690   Diesel   20  64.2   
141      C Class  2009   4200    Automatic    96000   Diesel  235  42.2   
500      C Class  2015  12495    Automatic    55000   Diesel   30  64.2   
727          SLK  2013   9600    Automatic    51458   Diesel  145  56.5   
1065   GLA Class  2014  13447    Automatic    54146   Diesel  145  55.4   
1122   CLS Class  2013  12210    Automatic    54238   Diesel  145  54.3   
1125     E Class  2014  13970    Automatic    51176   Diesel  200  47.1   
1153     E Class  2015  13527    Automatic    51933   Diesel  125  61.4   
1381   GLA Class  2014  13990    Automatic    56488   Diesel  145  55.4   
1396   CLS Class  2013  14750    Automatic    56198   Diesel  200  46.3   
1411    CL Class  2015  13490    Automatic    63797   Diesel   20  68.9   
1417     C Class  2016  14495    Automatic    50995   Diesel   30  64.2   

      engineSize  
49           2.0  
51           2.1  
59           2.1  
62           2.1  
66           2.1  
71           3.0  
72           1.8  
74           3.0  
75           3.0  
76           3.0  
79           3.0  
128          2.1  
141          2.1  
500          2.1  
727          2.0  
1065         2.1  
1122         2.1  
1125         3.0  
1153         2.1  
1381         2.1  
1396         3.0  
1411         2.1  
1417         1.6

In [42]:
df['ratio'] = (df['tax'] / df['price']) * 100
df.ratio

0       6.250000
1       0.057228
2       1.111156
3       0.524634
4       0.439498
          ...   
1497    0.659211
1498    0.775354
1499    0.735619
1500    0.690641
1501    0.726817
Name: ratio, Length: 1502, dtype: float64